class PhoneFormatError(Exception):
    ...
class EmailFormatError(Exception):
    ...
class MissingKeyError(Exception):
    ...
class WrongKeyError(Exception):
    ...
class EmailTypeError(Exception):
    ...
class OnlyEmailError(Exception):
    ...